name: ldhat
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - pandas
  - numpy
  - seaborn
  - python
  - scipy
  - pexpect
  - biopython
  - future
  - fastsimbac 
  - seq-gen
  - msprime>=1.1.0
